// Seed hand histories, loaded into the database on first run.
// Cards are two-character codes: rank (A K Q J T 9-2) + suit (s h d c). Money is in dollars.

export const hands = [
  {
    id: 'h1',
    sessionId: 's18',
    date: '2026-09-27',
    stakes: '$1/$2',
    game: 'NLH',
    title: 'Three streets of value with top pair',
    heroPosition: 'BTN',
    holeCards: ['As', 'Kd'],
    board: ['Kh', '7c', '2d', 'Qs', '3h'],
    potSize: 437,
    result: 217,
    verdict: 'good',
    tags: ['Value bet', '3-bet pot'],
    note: 'CO showed KJ. River sizing could go bigger against this player.',
    streets: [
      { name: 'Preflop', pot: 3, actions: [
        { actor: 'CO', verb: 'raises to', amount: 6 },
        { actor: 'Hero', verb: '3-bets to', amount: 20 },
        { actor: 'CO', verb: 'calls', amount: 14 },
      ] },
      { name: 'Flop', pot: 43, actions: [
        { actor: 'CO', verb: 'checks' },
        { actor: 'Hero', verb: 'bets', amount: 22 },
        { actor: 'CO', verb: 'calls', amount: 22 },
      ] },
      { name: 'Turn', pot: 87, actions: [
        { actor: 'CO', verb: 'checks' },
        { actor: 'Hero', verb: 'bets', amount: 55 },
        { actor: 'CO', verb: 'calls', amount: 55 },
      ] },
      { name: 'River', pot: 197, actions: [
        { actor: 'CO', verb: 'checks' },
        { actor: 'Hero', verb: 'bets', amount: 120 },
        { actor: 'CO', verb: 'calls', amount: 120 },
      ] },
    ],
  },
  {
    id: 'h2',
    sessionId: 's18',
    date: '2026-09-27',
    stakes: '$1/$2',
    game: 'NLH',
    title: 'Called a river shove with a set on a four-straight board',
    heroPosition: 'BB',
    holeCards: ['8h', '8c'],
    board: ['8d', 'Js', '9s', '2c', 'Ts'],
    potSize: 639,
    result: -319,
    verdict: 'mistake',
    tags: ['Big pot', 'Hero call'],
    note: 'Villain had KQ. This player never raises the river light at these stakes. Clear fold.',
    streets: [
      { name: 'Preflop', pot: 3, actions: [
        { actor: 'BTN', verb: 'raises to', amount: 6 },
        { actor: 'SB', verb: 'folds' },
        { actor: 'Hero', verb: 'calls', amount: 4 },
      ] },
      { name: 'Flop', pot: 13, actions: [
        { actor: 'Hero', verb: 'checks' },
        { actor: 'BTN', verb: 'bets', amount: 8 },
        { actor: 'Hero', verb: 'raises to', amount: 28 },
        { actor: 'BTN', verb: 'calls', amount: 20 },
      ] },
      { name: 'Turn', pot: 69, actions: [
        { actor: 'Hero', verb: 'bets', amount: 45 },
        { actor: 'BTN', verb: 'calls', amount: 45 },
      ] },
      { name: 'River', pot: 159, actions: [
        { actor: 'Hero', verb: 'bets', amount: 110 },
        { actor: 'BTN', verb: 'shoves', amount: 240 },
        { actor: 'Hero', verb: 'calls', amount: 130 },
      ] },
    ],
  },
  {
    id: 'h3',
    sessionId: 's15',
    date: '2026-09-19',
    stakes: '$1/$2',
    game: 'NLH',
    title: 'Queens run into aces in a 4-bet pot',
    heroPosition: 'CO',
    holeCards: ['Qh', 'Qs'],
    board: ['4c', '4d', '9h', 'Kc', '2s'],
    potSize: 383,
    result: -190,
    verdict: 'cooler',
    tags: ['4-bet pot', 'Big pot'],
    note: 'Flatting the 4-bet was fine. Very hard to find a fold on the river.',
    streets: [
      { name: 'Preflop', pot: 3, actions: [
        { actor: 'UTG', verb: 'raises to', amount: 6 },
        { actor: 'Hero', verb: '3-bets to', amount: 22 },
        { actor: 'UTG', verb: '4-bets to', amount: 60 },
        { actor: 'Hero', verb: 'calls', amount: 38 },
      ] },
      { name: 'Flop', pot: 123, actions: [
        { actor: 'UTG', verb: 'bets', amount: 40 },
        { actor: 'Hero', verb: 'calls', amount: 40 },
      ] },
      { name: 'Turn', pot: 203, actions: [
        { actor: 'UTG', verb: 'checks' },
        { actor: 'Hero', verb: 'checks' },
      ] },
      { name: 'River', pot: 203, actions: [
        { actor: 'UTG', verb: 'bets', amount: 90 },
        { actor: 'Hero', verb: 'calls', amount: 90 },
      ] },
    ],
  },
  {
    id: 'h4',
    sessionId: 's16',
    date: '2026-09-22',
    stakes: '$0.5/$1',
    game: 'NLH',
    title: 'Turned straight against a check-raise',
    heroPosition: 'SB',
    holeCards: ['7s', '6s'],
    board: ['5s', '8c', 'Kd', '4h'],
    potSize: 57,
    result: 26,
    verdict: 'good',
    tags: ['Blind vs blind'],
    note: 'Shoving the turn protects against the flush draw and gets called by worse sometimes.',
    streets: [
      { name: 'Preflop', pot: 1.5, actions: [
        { actor: 'Hero', verb: 'raises to', amount: 3 },
        { actor: 'BB', verb: 'calls', amount: 2 },
      ] },
      { name: 'Flop', pot: 6, actions: [
        { actor: 'Hero', verb: 'bets', amount: 2 },
        { actor: 'BB', verb: 'calls', amount: 2 },
      ] },
      { name: 'Turn', pot: 10, actions: [
        { actor: 'Hero', verb: 'bets', amount: 7 },
        { actor: 'BB', verb: 'raises to', amount: 21 },
        { actor: 'Hero', verb: 'shoves', amount: 94 },
        { actor: 'BB', verb: 'folds' },
      ] },
    ],
  },
  {
    id: 'h5',
    sessionId: 's14',
    date: '2026-09-16',
    stakes: '$0.5/$1',
    game: 'NLH',
    title: 'Opened K9 offsuit under the gun',
    heroPosition: 'UTG',
    holeCards: ['Kh', '9c'],
    board: ['As', '7d', '3c'],
    potSize: 28.5,
    result: -10,
    verdict: 'mistake',
    tags: ['Preflop', 'Range'],
    note: 'Outside my UTG range. Tighten early-position opens.',
    streets: [
      { name: 'Preflop', pot: 1.5, actions: [
        { actor: 'Hero', verb: 'raises to', amount: 3 },
        { actor: 'BTN', verb: '3-bets to', amount: 10 },
        { actor: 'Hero', verb: 'calls', amount: 7 },
      ] },
      { name: 'Flop', pot: 21.5, actions: [
        { actor: 'Hero', verb: 'checks' },
        { actor: 'BTN', verb: 'bets', amount: 7 },
        { actor: 'Hero', verb: 'folds' },
      ] },
    ],
  },
  {
    id: 'h6',
    sessionId: 's12',
    date: '2026-09-07',
    stakes: '$1/$2',
    game: 'PLO',
    title: 'Nut flush on the river in PLO',
    heroPosition: 'BTN',
    holeCards: ['Ah', 'Ad', 'Kh', 'Qs'],
    board: ['Jh', 'Th', '3c', '9d', '2h'],
    potSize: 305,
    result: 152,
    verdict: 'good',
    tags: ['PLO', 'Value bet'],
    note: 'Turned the straight, rivered the nut flush. Pot-sized river bet got called by a set.',
    streets: [
      { name: 'Preflop', pot: 3, actions: [
        { actor: 'Hero', verb: 'raises to', amount: 7 },
        { actor: 'BB', verb: 'calls', amount: 5 },
      ] },
      { name: 'Flop', pot: 15, actions: [
        { actor: 'BB', verb: 'checks' },
        { actor: 'Hero', verb: 'bets', amount: 15 },
        { actor: 'BB', verb: 'calls', amount: 15 },
      ] },
      { name: 'Turn', pot: 45, actions: [
        { actor: 'BB', verb: 'checks' },
        { actor: 'Hero', verb: 'bets', amount: 30 },
        { actor: 'BB', verb: 'calls', amount: 30 },
      ] },
      { name: 'River', pot: 105, actions: [
        { actor: 'BB', verb: 'checks' },
        { actor: 'Hero', verb: 'bets', amount: 100 },
        { actor: 'BB', verb: 'calls', amount: 100 },
      ] },
    ],
  },
  {
    id: 'h7',
    sessionId: 's13',
    date: '2026-09-12',
    stakes: '$1/$2',
    game: 'NLH',
    title: 'Missed-draw bluff on the river',
    heroPosition: 'BTN',
    holeCards: ['Jc', 'Tc'],
    board: ['Ac', '8s', '4d', '2h', '6s'],
    potSize: 81,
    result: -39,
    verdict: 'review',
    tags: ['Bluff', 'Single-raised pot'],
    note: 'Floating the flop with only backdoor draws was thin. Is this river bluff believable?',
    streets: [
      { name: 'Preflop', pot: 3, actions: [
        { actor: 'CO', verb: 'raises to', amount: 6 },
        { actor: 'Hero', verb: 'calls', amount: 6 },
      ] },
      { name: 'Flop', pot: 15, actions: [
        { actor: 'CO', verb: 'bets', amount: 8 },
        { actor: 'Hero', verb: 'calls', amount: 8 },
      ] },
      { name: 'Turn', pot: 31, actions: [
        { actor: 'CO', verb: 'checks' },
        { actor: 'Hero', verb: 'checks' },
      ] },
      { name: 'River', pot: 31, actions: [
        { actor: 'CO', verb: 'checks' },
        { actor: 'Hero', verb: 'bets', amount: 25 },
        { actor: 'CO', verb: 'calls', amount: 25 },
      ] },
    ],
  },
];
